[package]
name = "glfw"
version = "0.6.0"
authors = ["The glfw-rs developers."]
description = "GLFW3 bindings and idiomatic wrapper for Rust."
keywords = ["windowing", "opengl", "vulkan"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bjz/glfw-rs"

[features]
default = ["glfw-sys"]
vulkan = ["vk-sys"]

[dependencies]
semver = "0.2"
log = "0.3"
bitflags = "0.6"
libc = "0.2"
enum_primitive = "0.1"
num = "0.1"

[dependencies.glfw-sys]
version = "3.1.3"
optional = true

[dependencies.vk-sys]
version = "0.1.0"
optional = true
path = "../vulkano/vk-sys"
